services:
  redis:
    image: redis:7.2-alpine
    restart: unless-stopped
    ports:
      - '6379:6379'
    volumes:
      - redis:/data

  postgres:
    image: tensorchord/pgvecto-rs:pg16-v0.3.0
    restart: unless-stopped
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=fedibgs
    volumes:
      - postgres:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  redis:
  postgres:
